### PR TITLE
adding the ability to export just JSON

### PR DESCRIPTION
**Pull request by savar**
for other purposes than using the data within a dart project, the JSON
is often very helpful, so a new parameter allows to create a pure JSON
variant of it

* using 'args' module
* changed the parameter the command supports
* added the ability to export JSON

### CODE REVIEW

**Comment by savar** [comment]
this is just a very quick and maybe still dirty way to use the plugin as intermediate for other things not running in the dart language

**Comment by savar** [comment]
in case you are in favour of this merge request, I could then update the README.md and stuff as well to reflect the changed information

**Comment by lordgreg** [comment]
hi @espresso3389 - will this PR be merged or is do you require additional updates from @savar? I'd like to see this functionality in the code too. 

Thank you!

**Comment by lordgreg** [comment]
Maybe `--output` which is also quite standard name for the export you would like to do.

So, for this use-case:

1. If parameter `--output` is not available, use default implementation
2. If parameter `--output` is available, check if `dart`, then use default implementation
3. If parameter `--output` is available, check if `json`, then use JSON output implementation
4. If parameter `--output` is available, none from array of correct outputs (json or dart), then show error or syntax.

**Comment by espresso3389** [comment]
@lordgreg OK, it makes sense.

**Comment by espresso3389** [comment]
OK, anyway, I once merge the PR and make changes on it.

**Comment by espresso3389** [comment]
Mmm, `--output` option may be structurelly correct but the behavior may not be intuitive for users. Simple `--json` option may be better and enough...

**Comment by espresso3389** [comment]
I've just released [flutter_oss_licenses 1.1.2](https://pub.dev/packages/flutter_oss_licenses) that includes the PR!

**Comment by savar** [comment]
Thanks @espresso3389 .. sorry I completely lost track here and of course --output and/or --json are fine.

Thanks for merging it!

**Pull request merged**
